version: '3.8'
services:
  # Сервис для базы данных PostgreSQL
  db:

    build:
      context: .
      dockerfile: Dockerfile2
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=test'
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # Сервис для вашего Java-приложения с использованием Maven
  jp2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

    ports:
      - "8080:8080"

  # Сервис для фронтенд-приложения на Node.js

volumes:
  db: